<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-LRF84BSB" failures="1" tests="3" name="SubmitOrder" time="74.563" errors="0" timestamp="2024-05-12T16:28:21 IST">
  <testcase classname="com.tests.StandAloneTest" name="submitOrder" time="5.545"/>
  <testcase classname="com.tests.StandAloneTest" name="submitOrder" time="4.348"/>
  <testcase classname="com.tests.StandAloneTest" name="orderHistoryTest" time="1.247">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.tests.StandAloneTest.orderHistoryTest(StandAloneTest.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- orderHistoryTest -->
</testsuite> <!-- SubmitOrder -->
